### ISSUE TITLE
Url parsing is broken when there are special characters

### ISSUE THREAD

**Issue by knamburigsa** [GSA/sam-layouts#27]
Parsing is not working correctly when there are special characters in the query params
When you try to parse this query param using the following logic it is not working as expected.
`sfm%5BsimpleSearch%5D%5BkeywordRadio%5D=ALL&sfm%5BsimpleSearch%5D%5BkeywordTags%5D%5B0%5D%5Bkey%5D=%22at%26t%22&sfm%5BsimpleSearch%5D%5BkeywordTags%5D%5B0%5D%5Bvalue%5D=%22at%26t%22&sfm%5Bstatus%5D%5Bis_active%5D=true`

Expected:
`sfm: {
simpleSearch: {
keywordRadio: "ALL",
keywordTags: [{key: "\"at&t\"", value: "\"at&t\""}],
}
}`
Actual:
`sfm: {
simpleSearch: {
keywordRadio: "ALL",
keywordTags: [{key: "\"at", value: "\"at"}],
}
}`
![image](https://github.com/GSA/sam-layouts/assets/92172714/fc129f8b-e0c2-49ef-a642-68be40d04a8d)

https://github.com/GSA/sam-layouts/blob/angular-16/layouts/src/lib/search-list-layout/search-list-layout.component.ts#L348

**Comment by P-Kondapalli** [comment]
Duplicate to https://github.com/GSA/sam-layouts/issues/32. Closing the ticket.
