### ISSUE TITLE
Navigation is breaking when a filter consists '&' in the value.

### ISSUE THREAD

**Issue by knamburigsa** [GSA/sam-layouts#32]
When i update the filters in search page.
![image](https://user-images.githubusercontent.com/92172714/175667848-73dd595c-a3ca-4057-8eb2-faa7833e472c.png)

![image](https://user-images.githubusercontent.com/92172714/175668899-890eef9d-717f-4837-8136-6c7b9c46ea5a.png)

Reopening: https://github.com/GSA/sam-layouts/issues/8

IAEMOD-970

**Comment by P-Kondapalli** [comment]
As per discussion with @knamburigsa, this issue has been already fixed and it is working as expected in prod. Closing the ticket.
cc: @thomastighe
