### ISSUE TITLE
Need more flexibility on when the search is invoked

### ISSUE THREAD

**Issue by knamburigsa** [GSA/sam-layouts#7]
![image](https://user-images.githubusercontent.com/92172714/167912095-d9bd07de-bcf6-4a53-b714-9eefac12367f.png)
The default model has All for keyword search.
When a user selects a different radio button for Keyword search, new search call is being triggered because it is not the default model anymore.

We do not want to trigger a search call when only keyword search type changes.

IAE Ticket: IAEDEV-60884

**Comment by carlosvalle** [comment]
Hello,

You could use the pairwise and filter operator to prevent triggering the search for certain fields
Here a demo:  https://github.com/GSA/sam-layouts/tree/master/libs/layouts/src/lib/search-list-layout/demo

```javascript
    const filters$ = this.filterChange$.pipe(
      pairwise(),
      filter(([prev, curr]: any) => {
        return (
          prev.keyword.keywordRadio === curr.keyword.keywordRadio &&
          prev.keyword.keywordExactPhrase === curr.keyword.keywordExactPhrase
        );
      })
    );

    filters$.subscribe(([_, model]) => {
      this.resultList.updateFilter(model);
    });
```
